### ISSUE TITLE
OAUTH authentication

### ISSUE THREAD

**Issue by stephpy** [rezzza/vaultage#3]
```
Crypt{file} > ( (Key + Token) + Passphrase) > file
 
Token         <= https://remote.server/ {user:password}
Key            <= localFile
Passphrase <= Keyboardinput
```

Allow revocation of acces to a file/user.

**Comment by shouze** [comment]
ping @stephpy this is a very old one... close & tag it wontfix?

**Comment by stephpy** [comment]
It's an enhancement, anybody who want to make a PR is wellcome. :)

**Comment by shouze** [comment]
Closing this one as it's pretty outdated & no PR made.

**Comment by stephpy** [comment]
:scream_cat:
